# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/azt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/azt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/azt.proto\x12\x06\x61zt.v1\"\xe9\x01\n\rActionContext\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0c\n\x04tool\x18\x03 \x01(\t\x12\x39\n\nparameters\x18\x04 \x03(\x0b\x32%.azt.v1.ActionContext.ParametersEntry\x12\x13\n\x0btrust_score\x18\x05 \x01(\x05\x12\x12\n\nsession_id\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"<\n\x12\x45nforcementRequest\x12&\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x15.azt.v1.ActionContext\"z\n\x13\x45nforcementResponse\x12\"\n\x08\x64\x65\x63ision\x18\x01 \x01(\x0e\x32\x10.azt.v1.Decision\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x1b\n\x13updated_trust_score\x18\x03 \x01(\x05\x12\x12\n\nrequest_id\x18\x04 \x01(\t\"%\n\x11TrustScoreRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"3\n\x12TrustScoreResponse\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x0e\n\x06reason\x18\x02 \x01(\t*j\n\x08\x44\x65\x63ision\x12\x18\n\x14\x44\x45\x43ISION_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x44\x45\x43ISION_ALLOW\x10\x01\x12\x11\n\rDECISION_DENY\x10\x02\x12\x1d\n\x19\x44\x45\x43ISION_REQUIRE_APPROVAL\x10\x03\x32\x98\x01\n\nAZTGateway\x12\x42\n\x07\x45nforce\x12\x1a.azt.v1.EnforcementRequest\x1a\x1b.azt.v1.EnforcementResponse\x12\x46\n\rGetTrustScore\x12\x19.azt.v1.TrustScoreRequest\x1a\x1a.azt.v1.TrustScoreResponseB.Z,github.com/anzero/azt-framework/proto/azt/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.azt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/anzero/azt-framework/proto/azt/v1'
  _globals['_ACTIONCONTEXT_PARAMETERSENTRY']._loaded_options = None
  _globals['_ACTIONCONTEXT_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_DECISION']._serialized_start=541
  _globals['_DECISION']._serialized_end=647
  _globals['_ACTIONCONTEXT']._serialized_start=28
  _globals['_ACTIONCONTEXT']._serialized_end=261
  _globals['_ACTIONCONTEXT_PARAMETERSENTRY']._serialized_start=212
  _globals['_ACTIONCONTEXT_PARAMETERSENTRY']._serialized_end=261
  _globals['_ENFORCEMENTREQUEST']._serialized_start=263
  _globals['_ENFORCEMENTREQUEST']._serialized_end=323
  _globals['_ENFORCEMENTRESPONSE']._serialized_start=325
  _globals['_ENFORCEMENTRESPONSE']._serialized_end=447
  _globals['_TRUSTSCOREREQUEST']._serialized_start=449
  _globals['_TRUSTSCOREREQUEST']._serialized_end=486
  _globals['_TRUSTSCORERESPONSE']._serialized_start=488
  _globals['_TRUSTSCORERESPONSE']._serialized_end=539
  _globals['_AZTGATEWAY']._serialized_start=650
  _globals['_AZTGATEWAY']._serialized_end=802
# @@protoc_insertion_point(module_scope)
