// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: azt.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decision int32

const (
	Decision_DECISION_UNSPECIFIED      Decision = 0
	Decision_DECISION_ALLOW            Decision = 1
	Decision_DECISION_DENY             Decision = 2
	Decision_DECISION_REQUIRE_APPROVAL Decision = 3
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "DECISION_ALLOW",
		2: "DECISION_DENY",
		3: "DECISION_REQUIRE_APPROVAL",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED":      0,
		"DECISION_ALLOW":            1,
		"DECISION_DENY":             2,
		"DECISION_REQUIRE_APPROVAL": 3,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_azt_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_azt_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_azt_proto_rawDescGZIP(), []int{0}
}

type ActionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Tool          string                 `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TrustScore    int32                  `protobuf:"varint,5,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionContext) Reset() {
	*x = ActionContext{}
	mi := &file_azt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionContext) ProtoMessage() {}

func (x *ActionContext) ProtoReflect() protoreflect.Message {
	mi := &file_azt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionContext.ProtoReflect.Descriptor instead.
func (*ActionContext) Descriptor() ([]byte, []int) {
	return file_azt_proto_rawDescGZIP(), []int{0}
}

func (x *ActionContext) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ActionContext) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionContext) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ActionContext) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ActionContext) GetTrustScore() int32 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

func (x *ActionContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ActionContext) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type EnforcementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ActionContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnforcementRequest) Reset() {
	*x = EnforcementRequest{}
	mi := &file_azt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforcementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforcementRequest) ProtoMessage() {}

func (x *EnforcementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_azt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforcementRequest.ProtoReflect.Descriptor instead.
func (*EnforcementRequest) Descriptor() ([]byte, []int) {
	return file_azt_proto_rawDescGZIP(), []int{1}
}

func (x *EnforcementRequest) GetContext() *ActionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type EnforcementResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Decision          Decision               `protobuf:"varint,1,opt,name=decision,proto3,enum=azt.v1.Decision" json:"decision,omitempty"`
	Reason            string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	UpdatedTrustScore int32                  `protobuf:"varint,3,opt,name=updated_trust_score,json=updatedTrustScore,proto3" json:"updated_trust_score,omitempty"`
	RequestId         string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnforcementResponse) Reset() {
	*x = EnforcementResponse{}
	mi := &file_azt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforcementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforcementResponse) ProtoMessage() {}

func (x *EnforcementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_azt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforcementResponse.ProtoReflect.Descriptor instead.
func (*EnforcementResponse) Descriptor() ([]byte, []int) {
	return file_azt_proto_rawDescGZIP(), []int{2}
}

func (x *EnforcementResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *EnforcementResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EnforcementResponse) GetUpdatedTrustScore() int32 {
	if x != nil {
		return x.UpdatedTrustScore
	}
	return 0
}

func (x *EnforcementResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type TrustScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustScoreRequest) Reset() {
	*x = TrustScoreRequest{}
	mi := &file_azt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustScoreRequest) ProtoMessage() {}

func (x *TrustScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_azt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustScoreRequest.ProtoReflect.Descriptor instead.
func (*TrustScoreRequest) Descriptor() ([]byte, []int) {
	return file_azt_proto_rawDescGZIP(), []int{3}
}

func (x *TrustScoreRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type TrustScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Breakdown     *FactorBreakdown       `protobuf:"bytes,3,opt,name=breakdown,proto3" json:"breakdown,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustScoreResponse) Reset() {
	*x = TrustScoreResponse{}
	mi := &file_azt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustScoreResponse) ProtoMessage() {}

func (x *TrustScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_azt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustScoreResponse.ProtoReflect.Descriptor instead.
func (*TrustScoreResponse) Descriptor() ([]byte, []int) {
	return file_azt_proto_rawDescGZIP(), []int{4}
}

func (x *TrustScoreResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TrustScoreResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TrustScoreResponse) GetBreakdown() *FactorBreakdown {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

func (x *TrustScoreResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type UpdateTrustScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Factor        string                 `protobuf:"bytes,2,opt,name=factor,proto3" json:"factor,omitempty"`
	Delta         int32                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	ActionContext map[string]string      `protobuf:"bytes,5,rep,name=action_context,json=actionContext,proto3" json:"action_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTrustScoreRequest) Reset() {
	*x = UpdateTrustScoreRequest{}
	mi := &file_azt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrustScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrustScoreRequest) ProtoMessage() {}

func (x *UpdateTrustScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_azt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrustScoreRequest.ProtoReflect.Descriptor instead.
func (*UpdateTrustScoreRequest) Descriptor() ([]byte, []int) {
	return file_azt_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTrustScoreRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UpdateTrustScoreRequest) GetFactor() string {
	if x != nil {
		return x.Factor
	}
	return ""
}

func (x *UpdateTrustScoreRequest) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *UpdateTrustScoreRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateTrustScoreRequest) GetActionContext() map[string]string {
	if x != nil {
		return x.ActionContext
	}
	return nil
}

type GetAgentScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentScoreRequest) Reset() {
	*x = GetAgentScoreRequest{}
	mi := &file_azt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentScoreRequest) ProtoMessage() {}

func (x *GetAgentScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_azt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentScoreRequest.ProtoReflect.Descriptor instead.
func (*GetAgentScoreRequest) Descriptor() ([]byte, []int) {
	return file_azt_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentScoreRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type FactorBreakdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      int32                  `protobuf:"varint,1,opt,name=identity,proto3" json:"identity,omitempty"`
	History       int32                  `protobuf:"varint,2,opt,name=history,proto3" json:"history,omitempty"`
	Time          int32                  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Anomaly       int32                  `protobuf:"varint,4,opt,name=anomaly,proto3" json:"anomaly,omitempty"`
	Frequency     int32                  `protobuf:"varint,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactorBreakdown) Reset() {
	*x = FactorBreakdown{}
	mi := &file_azt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorBreakdown) ProtoMessage() {}

func (x *FactorBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_azt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorBreakdown.ProtoReflect.Descriptor instead.
func (*FactorBreakdown) Descriptor() ([]byte, []int) {
	return file_azt_proto_rawDescGZIP(), []int{7}
}

func (x *FactorBreakdown) GetIdentity() int32 {
	if x != nil {
		return x.Identity
	}
	return 0
}

func (x *FactorBreakdown) GetHistory() int32 {
	if x != nil {
		return x.History
	}
	return 0
}

func (x *FactorBreakdown) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *FactorBreakdown) GetAnomaly() int32 {
	if x != nil {
		return x.Anomaly
	}
	return 0
}

func (x *FactorBreakdown) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type ThreatShieldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Tool          string                 `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Output        string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TrustScore    int32                  `protobuf:"varint,7,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatShieldRequest) Reset() {
	*x = ThreatShieldRequest{}
	mi := &file_azt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatShieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatShieldRequest) ProtoMessage() {}

func (x *ThreatShieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_azt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatShieldRequest.ProtoReflect.Descriptor instead.
func (*ThreatShieldRequest) Descriptor() ([]byte, []int) {
	return file_azt_proto_rawDescGZIP(), []int{8}
}

func (x *ThreatShieldRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ThreatShieldRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ThreatShieldRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ThreatShieldRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ThreatShieldRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ThreatShieldRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ThreatShieldRequest) GetTrustScore() int32 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

func (x *ThreatShieldRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ThreatShieldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      string                 `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	SeverityScore int32                  `protobuf:"varint,2,opt,name=severity_score,json=severityScore,proto3" json:"severity_score,omitempty"`
	Indicators    []string               `protobuf:"bytes,3,rep,name=indicators,proto3" json:"indicators,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatShieldResponse) Reset() {
	*x = ThreatShieldResponse{}
	mi := &file_azt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatShieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatShieldResponse) ProtoMessage() {}

func (x *ThreatShieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_azt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatShieldResponse.ProtoReflect.Descriptor instead.
func (*ThreatShieldResponse) Descriptor() ([]byte, []int) {
	return file_azt_proto_rawDescGZIP(), []int{9}
}

func (x *ThreatShieldResponse) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ThreatShieldResponse) GetSeverityScore() int32 {
	if x != nil {
		return x.SeverityScore
	}
	return 0
}

func (x *ThreatShieldResponse) GetIndicators() []string {
	if x != nil {
		return x.Indicators
	}
	return nil
}

func (x *ThreatShieldResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_azt_proto protoreflect.FileDescriptor

const file_azt_proto_rawDesc = "" +
	"\n" +
	"\tazt.proto\x12\x06azt.v1\"\xba\x02\n" +
	"\rActionContext\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\x12E\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2%.azt.v1.ActionContext.ParametersEntryR\n" +
	"parameters\x12\x1f\n" +
	"\vtrust_score\x18\x05 \x01(\x05R\n" +
	"trustScore\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x12EnforcementRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.azt.v1.ActionContextR\acontext\"\xaa\x01\n" +
	"\x13EnforcementResponse\x12,\n" +
	"\bdecision\x18\x01 \x01(\x0e2\x10.azt.v1.DecisionR\bdecision\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12.\n" +
	"\x13updated_trust_score\x18\x03 \x01(\x05R\x11updatedTrustScore\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\".\n" +
	"\x11TrustScoreRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x94\x01\n" +
	"\x12TrustScoreResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x125\n" +
	"\tbreakdown\x18\x03 \x01(\v2\x17.azt.v1.FactorBreakdownR\tbreakdown\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\"\x97\x02\n" +
	"\x17UpdateTrustScoreRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06factor\x18\x02 \x01(\tR\x06factor\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x05R\x05delta\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12Y\n" +
	"\x0eaction_context\x18\x05 \x03(\v22.azt.v1.UpdateTrustScoreRequest.ActionContextEntryR\ractionContext\x1a@\n" +
	"\x12ActionContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\x14GetAgentScoreRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x93\x01\n" +
	"\x0fFactorBreakdown\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\x05R\bidentity\x12\x18\n" +
	"\ahistory\x18\x02 \x01(\x05R\ahistory\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x05R\x04time\x12\x18\n" +
	"\aanomaly\x18\x04 \x01(\x05R\aanomaly\x12\x1c\n" +
	"\tfrequency\x18\x05 \x01(\x05R\tfrequency\"\xd7\x02\n" +
	"\x13ThreatShieldRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12K\n" +
	"\n" +
	"parameters\x18\x06 \x03(\v2+.azt.v1.ThreatShieldRequest.ParametersEntryR\n" +
	"parameters\x12\x1f\n" +
	"\vtrust_score\x18\a \x01(\x05R\n" +
	"trustScore\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x01\n" +
	"\x14ThreatShieldResponse\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\tR\bdecision\x12%\n" +
	"\x0eseverity_score\x18\x02 \x01(\x05R\rseverityScore\x12\x1e\n" +
	"\n" +
	"indicators\x18\x03 \x03(\tR\n" +
	"indicators\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason*j\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDECISION_ALLOW\x10\x01\x12\x11\n" +
	"\rDECISION_DENY\x10\x02\x12\x1d\n" +
	"\x19DECISION_REQUIRE_APPROVAL\x10\x032\x83\x03\n" +
	"\n" +
	"AZTGateway\x12B\n" +
	"\aEnforce\x12\x1a.azt.v1.EnforcementRequest\x1a\x1b.azt.v1.EnforcementResponse\x12F\n" +
	"\rGetTrustScore\x12\x19.azt.v1.TrustScoreRequest\x1a\x1a.azt.v1.TrustScoreResponse\x12O\n" +
	"\x10UpdateTrustScore\x12\x1f.azt.v1.UpdateTrustScoreRequest\x1a\x1a.azt.v1.TrustScoreResponse\x12I\n" +
	"\rGetAgentScore\x12\x1c.azt.v1.GetAgentScoreRequest\x1a\x1a.azt.v1.TrustScoreResponse\x12M\n" +
	"\x10ThreatShieldScan\x12\x1b.azt.v1.ThreatShieldRequest\x1a\x1c.azt.v1.ThreatShieldResponseB.Z,github.com/anzero/azt-framework/proto/azt/v1b\x06proto3"

var (
	file_azt_proto_rawDescOnce sync.Once
	file_azt_proto_rawDescData []byte
)

func file_azt_proto_rawDescGZIP() []byte {
	file_azt_proto_rawDescOnce.Do(func() {
		file_azt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_azt_proto_rawDesc), len(file_azt_proto_rawDesc)))
	})
	return file_azt_proto_rawDescData
}

var file_azt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_azt_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_azt_proto_goTypes = []any{
	(Decision)(0),                   // 0: azt.v1.Decision
	(*ActionContext)(nil),           // 1: azt.v1.ActionContext
	(*EnforcementRequest)(nil),      // 2: azt.v1.EnforcementRequest
	(*EnforcementResponse)(nil),     // 3: azt.v1.EnforcementResponse
	(*TrustScoreRequest)(nil),       // 4: azt.v1.TrustScoreRequest
	(*TrustScoreResponse)(nil),      // 5: azt.v1.TrustScoreResponse
	(*UpdateTrustScoreRequest)(nil), // 6: azt.v1.UpdateTrustScoreRequest
	(*GetAgentScoreRequest)(nil),    // 7: azt.v1.GetAgentScoreRequest
	(*FactorBreakdown)(nil),         // 8: azt.v1.FactorBreakdown
	(*ThreatShieldRequest)(nil),     // 9: azt.v1.ThreatShieldRequest
	(*ThreatShieldResponse)(nil),    // 10: azt.v1.ThreatShieldResponse
	nil,                             // 11: azt.v1.ActionContext.ParametersEntry
	nil,                             // 12: azt.v1.UpdateTrustScoreRequest.ActionContextEntry
	nil,                             // 13: azt.v1.ThreatShieldRequest.ParametersEntry
}
var file_azt_proto_depIdxs = []int32{
	11, // 0: azt.v1.ActionContext.parameters:type_name -> azt.v1.ActionContext.ParametersEntry
	1,  // 1: azt.v1.EnforcementRequest.context:type_name -> azt.v1.ActionContext
	0,  // 2: azt.v1.EnforcementResponse.decision:type_name -> azt.v1.Decision
	8,  // 3: azt.v1.TrustScoreResponse.breakdown:type_name -> azt.v1.FactorBreakdown
	12, // 4: azt.v1.UpdateTrustScoreRequest.action_context:type_name -> azt.v1.UpdateTrustScoreRequest.ActionContextEntry
	13, // 5: azt.v1.ThreatShieldRequest.parameters:type_name -> azt.v1.ThreatShieldRequest.ParametersEntry
	2,  // 6: azt.v1.AZTGateway.Enforce:input_type -> azt.v1.EnforcementRequest
	4,  // 7: azt.v1.AZTGateway.GetTrustScore:input_type -> azt.v1.TrustScoreRequest
	6,  // 8: azt.v1.AZTGateway.UpdateTrustScore:input_type -> azt.v1.UpdateTrustScoreRequest
	7,  // 9: azt.v1.AZTGateway.GetAgentScore:input_type -> azt.v1.GetAgentScoreRequest
	9,  // 10: azt.v1.AZTGateway.ThreatShieldScan:input_type -> azt.v1.ThreatShieldRequest
	3,  // 11: azt.v1.AZTGateway.Enforce:output_type -> azt.v1.EnforcementResponse
	5,  // 12: azt.v1.AZTGateway.GetTrustScore:output_type -> azt.v1.TrustScoreResponse
	5,  // 13: azt.v1.AZTGateway.UpdateTrustScore:output_type -> azt.v1.TrustScoreResponse
	5,  // 14: azt.v1.AZTGateway.GetAgentScore:output_type -> azt.v1.TrustScoreResponse
	10, // 15: azt.v1.AZTGateway.ThreatShieldScan:output_type -> azt.v1.ThreatShieldResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_azt_proto_init() }
func file_azt_proto_init() {
	if File_azt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_azt_proto_rawDesc), len(file_azt_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_azt_proto_goTypes,
		DependencyIndexes: file_azt_proto_depIdxs,
		EnumInfos:         file_azt_proto_enumTypes,
		MessageInfos:      file_azt_proto_msgTypes,
	}.Build()
	File_azt_proto = out.File
	file_azt_proto_goTypes = nil
	file_azt_proto_depIdxs = nil
}
