// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.1
// source: proto/azt.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AZTGateway_Enforce_FullMethodName       = "/azt.v1.AZTGateway/Enforce"
	AZTGateway_GetTrustScore_FullMethodName = "/azt.v1.AZTGateway/GetTrustScore"
)

// AZTGatewayClient is the client API for AZTGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AZTGatewayClient interface {
	Enforce(ctx context.Context, in *EnforcementRequest, opts ...grpc.CallOption) (*EnforcementResponse, error)
	GetTrustScore(ctx context.Context, in *TrustScoreRequest, opts ...grpc.CallOption) (*TrustScoreResponse, error)
}

type aZTGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewAZTGatewayClient(cc grpc.ClientConnInterface) AZTGatewayClient {
	return &aZTGatewayClient{cc}
}

func (c *aZTGatewayClient) Enforce(ctx context.Context, in *EnforcementRequest, opts ...grpc.CallOption) (*EnforcementResponse, error) {
	out := new(EnforcementResponse)
	err := c.cc.Invoke(ctx, AZTGateway_Enforce_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aZTGatewayClient) GetTrustScore(ctx context.Context, in *TrustScoreRequest, opts ...grpc.CallOption) (*TrustScoreResponse, error) {
	out := new(TrustScoreResponse)
	err := c.cc.Invoke(ctx, AZTGateway_GetTrustScore_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AZTGatewayServer is the server API for AZTGateway service.
// All implementations must embed UnimplementedAZTGatewayServer
// for forward compatibility
type AZTGatewayServer interface {
	Enforce(context.Context, *EnforcementRequest) (*EnforcementResponse, error)
	GetTrustScore(context.Context, *TrustScoreRequest) (*TrustScoreResponse, error)
	mustEmbedUnimplementedAZTGatewayServer()
}

// UnimplementedAZTGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedAZTGatewayServer struct {
}

func (UnimplementedAZTGatewayServer) Enforce(context.Context, *EnforcementRequest) (*EnforcementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enforce not implemented")
}
func (UnimplementedAZTGatewayServer) GetTrustScore(context.Context, *TrustScoreRequest) (*TrustScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrustScore not implemented")
}
func (UnimplementedAZTGatewayServer) mustEmbedUnimplementedAZTGatewayServer() {}

// UnsafeAZTGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AZTGatewayServer will
// result in compilation errors.
type UnsafeAZTGatewayServer interface {
	mustEmbedUnimplementedAZTGatewayServer()
}

func RegisterAZTGatewayServer(s grpc.ServiceRegistrar, srv AZTGatewayServer) {
	s.RegisterService(&AZTGateway_ServiceDesc, srv)
}

func _AZTGateway_Enforce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnforcementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AZTGatewayServer).Enforce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AZTGateway_Enforce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AZTGatewayServer).Enforce(ctx, req.(*EnforcementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AZTGateway_GetTrustScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrustScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AZTGatewayServer).GetTrustScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AZTGateway_GetTrustScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AZTGatewayServer).GetTrustScore(ctx, req.(*TrustScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AZTGateway_ServiceDesc is the grpc.ServiceDesc for AZTGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AZTGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "azt.v1.AZTGateway",
	HandlerType: (*AZTGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enforce",
			Handler:    _AZTGateway_Enforce_Handler,
		},
		{
			MethodName: "GetTrustScore",
			Handler:    _AZTGateway_GetTrustScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/azt.proto",
}
